;; Base de fait

(setq *BF* '(
	(semestre 2)
	(periode P)
	(provenance TC)
	(filiere NIL)
	(CreditsCS 18)
	(CreditsTM 6)
	(CreditsCSTM (+ CreditsCS CreditsTM))
	(FQ01 non_validee)
	(GE37 non_validee)
	(IA01 validee)
	(IA02 non_validee)
	(IA03 non_validee)
	(IA04 non_validee)
	(LO17 non_validee)
	(LO21 non_validee)
	(LO22 non_validee)
	(LO23 non_validee)
	(MB11 non_validee)
	(MI01 non_validee)
	(MI11 non_validee)
	(MI12 non_validee)
	(MP02 non_validee)
	(MP03 non_validee)
	(MT09 non_validee)
	(MT10 non_validee)
	(MT12 non_validee)
	(NF11 non_validee)
	(NF16 validee)
	(NF17 non_validee)
	(NF26 non_validee)
	(NF28 non_validee)
	(NF29 non_validee)
	(RO05 non_validee)
	(RO06 non_validee)
	(SR01 validee)
	(SR02 non_validee)
	(SR03 non_validee)
	(SR04 non_validee)
	(SR05 non_validee)
	(SR06 non_validee)
	(SY02 validee)
	(SY09 non_validee)
	(SY15 non_validee)
	(SY19 non_validee)	
	(SY23 non_validee)
	

	(LA12 validee)
	(LA13 non_validee)
))