;; Base de fait de batard

(setq *BF* '(
	(semestre 2)
	(periode P)
	(provenance TC)
	(filiere NIL)
	(CreditsCS 18)
	(CreditsTM 6)
	(CreditsCSTM (+ CreditsCS  CreditsTM))
	(FQ01 non_validee)
	(GE37 non_validee)
	(IA01 validee)
	(IA02 non_validee)
	(IA03 non_validee)
	(IA04 non_validee)
	(LO17 non_validee)
	(LO21 non_validee)
	(LO22 non_validee)
	(LO23 non_validee)
	(MB11 non_validee)
	(MI01 non_validee)
	(MI11 non_validee)
	(MI12 non_validee)
	(MP02 non_validee)
	(MP03 non_validee)
	(MT09 non_validee)
	(MT10 non_validee)
	(MT12 non_validee)
	(NF11 non_validee)
	(NF16 validee)
	(NF17 non_validee)
	(NF26 non_validee)
	(NF28 non_validee)
	(NF29 non_validee)
	(RO05 non_validee)
	(RO06 non_validee)
	(SR01 validee)
	(SR02 non_validee)
	(SR03 non_validee)
	(SR04 non_validee)
	(SR05 non_validee)
	(SR06 non_validee)
	(SY02 validee)
	(SY09 non_validee)
	(SY15 non_validee)
	(SY19 non_validee)	
	(SY23 non_validee)
	(LA12 validee)
	(LA13 non_validee)
))

(load "/home/valentin/git/IA01/services.lisp")

(setq *BF* NIL)


(defun main()

	(format T "Salut mon ami ! Si tu es là c'est que tu es une peu perdu pour choisir ~%")
	(format T "tes UVs. Mais pas de problème, j'ai la solution ! Je vais te poser ~%")
	(format T "quelques questions sur ton parcours à l'UTC et à partir de ça, je vais te ~%")
	(format T "suggérer un ensemble d'UVs que tu pourrais faire ce semestre ! ~%")
	(format T " ~%")

	(format T "Voulez-vous prendre un dossier etudiant (pour faire une demo) ou bien construire le tiens ? ~%( Réponses : prefabriquer / initialiser) ~%")
		(let ((answer (read-line)))

		; Check reponse correcte
		(loop while (and (not (equal answer "prefabriquer")) (not (equal answer "initialiser"))) do
			(print "Veuillez rentrer seulement prefabriquer ou initialiser ")
			(setq answer (read-line))
		)

		(if (equal answer "initialiser")
			(progn
				(format T "C'est parti, on va s'occuper de ton cas ! ~%~%")
				(createBF)
				(displayBF)
			)
			(progn
				(format T "Très bien ! On va prendre le cas de Jean-Karim, un étudiant qui rentre en GI02 !~%~% ")
				(setq *BF* '(
					(semestre 2)
					(periode P)
					(provenance TC)
					(filiere NIL)
					(CreditsCS 18)
					(CreditsTM 6)
					(CreditsCSTM (+ CreditsCS  CreditsTM))
					(FQ01 non_validee)
					(GE37 non_validee)
					(IA01 validee)
					(IA02 non_validee)
					(IA03 non_validee)
					(IA04 non_validee)
					(LO17 non_validee)
					(LO21 non_validee)
					(LO22 non_validee)
					(LO23 non_validee)
					(MB11 non_validee)
					(MI01 non_validee)
					(MI11 non_validee)
					(MI12 non_validee)
					(MP02 non_validee)
					(MP03 non_validee)
					(MT09 non_validee)
					(MT10 non_validee)
					(MT12 non_validee)
					(NF11 non_validee)
					(NF16 validee)
					(NF17 non_validee)
					(NF26 non_validee)
					(NF28 non_validee)
					(NF29 non_validee)
					(RO05 non_validee)
					(RO06 non_validee)
					(SR01 validee)
					(SR02 non_validee)
					(SR03 non_validee)
					(SR04 non_validee)
					(SR05 non_validee)
					(SR06 non_validee)
					(SY02 validee)
					(SY09 non_validee)
					(SY15 non_validee)
					(SY19 non_validee)	
					(SY23 non_validee)
					(LA12 validee)
					(LA13 non_validee)
				))
				(format T "Son dossier etudiant est le suivant : ~%")
				(displayBF)
			)
		)
	)
)
		