(defparameter *BF* '(
 		(Credits_CS 0)
 		(Credits_TM 0)
 		(credits_TSH 0)
 		(CS_POSSIBLES nil)
 		(TM_POSSIBLES nil)
 		(TSH_POSSIBLES nil)
 		(NB_UV 0)
 		(NB_CS 0)
 		(NB_TM 0)
 		(NB_TSH 0)
 		(SEMESTRE 0)

 		(BI01 "non_validee")
		(FQ01 "non_validee")
		(GE37 "non_validee")
		(GE38 "non_validee")
		(GE39 "non_validee")
		(GE40 "non_validee")
		(IA01 "non_validee")
		(IA02 "non_validee")
		(IA03 "non_validee")
		(IA04 "non_validee")
		(LO17 "non_validee")
		(LO21 "non_validee")
		(LO22 "non_validee")
		(LO23 "non_validee")
		(MB11 "non_validee")
		(MI01 "non_validee")
		(MI11 "non_validee")
		(MI12 "non_validee")
		(MP02 "non_validee")
		(MP03 "non_validee")
		(MT09 "non_validee")
		(MT10 "non_validee")
		(MT12 "non_validee")
		(NF11 "non_validee")
		(NF16 "non_validee")
		(NA17 "non_validee")
		(NF17 "non_validee")
		(NF26 "non_validee")
		(NF28 "non_validee")
		(NF29 "non_validee")
		(RV01 "non_validee")
		(RO03 "non_validee")
		(RO04 "non_validee")
		(RO05 "non_validee")
		(RO06 "non_validee")
		(SR01 "non_validee")
		(SR02 "non_validee")
		(SR03 "non_validee")
		(SR04 "non_validee")
		(SR05 "non_validee")
		(SR06 "non_validee")
		(SY02 "non_validee")
		(SY06 "non_validee")
		(SY08 "non_validee")
		(SY09 "non_validee")
		(SY14 "non_validee")
		(SY15 "non_validee")
		(SY19 "non_validee")	
		(SY26 "non_validee")
		(SY27 "non_validee")
		(SY31 "non_validee")
		(SY32 "non_validee")
		(EI03 "non_validee") ; Communication
		(GE10 "non_validee") ; Economie
		(GE15 "non_validee") ; Entreprise
		(GE21 "non_validee") ; Economie
		(GE22 "non_validee") ; Economie
		(GE25 "non_validee")
		(GE27 "non_validee")
		(GE36 "non_validee") ; Marketing / Entreprise
		(HE03 "non_validee") ; Logique
		(IC05 "non_validee") ; Représentation
		(LA00 "non_validee")
		(LA01 "non_validee")
		(LA02 "non_validee")
		(LA03 "non_validee")
		(LA12 "non_validee")
		(LA13 "non_validee")
		(LA20 "non_validee")
		(LA21 "non_validee")
		(LA22 "non_validee")
		(LA23 "non_validee")
		(LG60 "non_validee") ; Tching Tchong
		(LG61 "non_validee")
		(LG62 "non_validee") ; Master Tching Tchong 
		(PH01 "non_validee") ; Philo
		(PH03 "non_validee") ; Philo
		(PH10 "non_validee") ; Philo
		(SI28 "non_validee") ; Ecriture interactive et multimedia
		(SP01 "non_validee") ; Sport
))